### ISSUE TITLE
请问怎么让替换过程无感呢？现在会有一个有空格到没空格的过度。

### ISSUE THREAD

**Issue by rebron1900** [backrunner/pangu.simple.js#21]
如题，浏览体验不太好。

**Comment by backrunner** [comment]
解决问题的办法和具体case详情紧密相关，由于没有提供，我只能给出一个大致的方向。

对于不需要远程拉取的文本，可以考虑通过CSS给页面需要插入空格的内容先设置为不可见（如设置display、visibility、opacity属性，设置在包裹需插入空格内容的容器上，如果是处理整个页面，那就加在html或者body上），在pangu执行完成后显示相关内容。

对于需要远程拉取的本文，可以使用spacing处理完成后再渲染。

**Comment by rebron1900** [comment]
http://1900.live 我现在用在我的博客上面，页面加载后会有很明显的字体位移的过程，想优化下这个显示过程。

**Comment by backrunner** [comment]
> http://1900.live 我现在用在我的博客上面，页面加载后会有很明显的字体位移的过程，想优化下这个显示过程。

可以参照上面我的建议进行修改，你可以修改你的博客主题或者嵌入一段额外的js，将页面的body元素先隐藏，执行完pangu之后再重置css样式，将其展示出来。

**Comment by rebron1900** [comment]
> 

但是现在没有回调函数，我怎么才能知道他执行完毕了呢？

**Comment by backrunner** [comment]
> > 
> 
> 但是现在没有回调函数，我怎么才能知道他执行完毕了呢？

我看了下你的站点，其实每一页最终都是静态的，在这种情况下你可以不需要使用 `autoSpacingPage`，在每一页所有内容的最后（例如在body标签内的最后）插入一行 `pangu.spacingPage()` 即可，这个函数是同步的。`autoSpacingPage` 本身默认存在一个delay，而且这个函数没有回调可用。

**Comment by rebron1900** [comment]
好谢谢，我测试一下。

**Comment by rebron1900** [comment]
谢谢，刚刚试了一下，虽然还是有，但是感觉没那么严重了。
