### ISSUE TITLE
调用autoSpacingPage()导致进程阻塞，页面卡死

### ISSUE THREAD

**Issue by rebron1900** [backrunner/pangu.simple.js#31]
出问题的页面 [https://1900.live/douban](https://1900.live/douban)，这个页面用过前端模板函数动态渲染了大量douban电影数据。

我之后通过性能检测工具发现在调用 autoSpacingPage 后 spacingNode 、 spacingNodeByXPath 两个函数会阻塞了进程，不知道是什么原因。我尝试将调用函数换成 spacingPageBody() 后页面性能恢复正常。猜测可能是body之外的某些标签阻塞了函数执行，大佬知道是什么原因吗？

![image](https://github.com/backrunner/pangu.simple.js/assets/7929884/df41fbdb-16ec-495e-9e4c-2a549ae58f03)

**Comment by backrunner** [comment]
spacing 是同步操作，会阻塞线程，autoSpacingPage 的原理是基于 MutationObserver 对页面的 DOM 进行监听，当页面结构发生变化，会对页面所有变更的 DOM 做一次遍历，进行 spacing。由于你的页面在全部 Tab 下，页面一次性插入的 DOM 过多（超过 1000 个），批量同步执行检查、正则替换肯定是有性能问题的，特别是在机器性能不太好的情况下。

而对于 spacingPageBody 你的执行时机比较早，瀑布流还没出来，如果瀑布流渲染出来之后再执行会有一样的效能问题。

如果需要对瀑布流元素进行 spacing，建议手动在代码里使用 `spacingText` 处理好文本，再进行渲染。
